networks:
  app-network:
    driver: bridge
services:
  api:
    build: ./api
    restart: always
    ports:
      - 6001:6001
    env_file:
      - path: ./vault/api.env
        required: true
    networks:
      - app-network
  bot:
    build: ./bot
    restart: always
    env_file:
      - ./vault/bot.env
    networks:
      - app-network
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./vault/cert.pem:/credentials/cert.pem
      - ./vault/key.pem:/credentials/key.pem
    networks:
      - app-network
    depends_on:
      - api
volumes:
  data:
